version: '3.1'
services:
  pg_db:
    container_name: postgresql-db
    image: postgres:15rc1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: parma_db
    ports:
      - "5438:5432"

  flyway:
    image: flyway/flyway:9.20-alpine
    command: -schemas=public -connectRetries=60 migrate
    volumes:
      - ./database/sql:/flyway/sql
#      - ./database/conf/flyway.conf:/flyway/conf/flyway.config
    depends_on:
      - pg_db
    environment:
      FLYWAY_URL: jdbc:postgresql://pg_db:5432/parma_db
      FLYWAY_USER: admin
      FLYWAY_PASSWORD: admin
      FLYWAY_BASELINE_ON_MIGRATE: "false"
