server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html



spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/parma_db
    username: admin
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        web=INFO:
files:
  baseDir: "resources_dir//"
api:
  version: @project.version@


