create type roles as enum ('ROOT', 'ADMIN', 'ADMIN_SCOPES', 'USER');

alter type roles owner to admin;

create table tag
(
    id           serial
        primary key,
    letter       varchar(250) not null,
    bkg_color    varchar      not null,
    letter_color varchar      not null
);

alter table tag
    owner to admin;

create unique index tag_letter_bkg_color_letter_color_uindex
    on tag (letter, bkg_color, letter_color);

create table users
(
    id                          integer generated by default as identity
        constraint user_pkey
            primary key,
    name                        varchar(40)           not null
        unique,
    password                    varchar(255)          not null,
    blocked                     boolean default false not null,
    is_admin_manager            boolean default false not null,
    is_admin_scope_manager      boolean default false not null,
    can_create_and_delete_scope boolean default false,
    max_number_scope            integer default 0,
    max_storage_space           integer default 0,
    max_number_folder           integer default 0
);

alter table users
    owner to admin;

create table file
(
    id           integer generated always as identity
        primary key,
    name         varchar(255)              not null,
    size         double precision          not null,
    type         varchar                   not null,
    date_created date default CURRENT_DATE not null,
    location     varchar                   not null,
    tag_id       integer
        constraint file_file_id_fk
            references tag
);

alter table file
    owner to admin;

create table scope
(
    id                        integer generated always as identity
        primary key,
    title                     varchar(20)           not null
        unique,
    description               varchar(1000),
    copyright                 varchar(40),
    show_illustrations        boolean default false not null,
    icon_id                   integer
        constraint icon_id_fk
            references file
            on delete set null,
    distribution_agreement_id integer
        constraint scope_distr_agreement_fk
            references file
            on delete set null
);

alter table scope
    owner to admin;

create table folder
(
    id              integer generated always as identity
        primary key,
    scope_id        integer               not null
        references scope
            on delete cascade,
    title           varchar(50)           not null,
    publish         boolean default false not null,
    manifest_ios    boolean default false not null,
    identifier      varchar(30),
    manifest_ios_id integer
        constraint folder_manifest_ios_id_fk
            references file
            on delete set null,
    constraint folder_title_title1_key
        unique (title, scope_id)
);

alter table folder
    owner to admin;

create table version
(
    id                  serial
        primary key,
    version_number      varchar(10)                  not null,
    date_of_publication date    default CURRENT_DATE not null,
    description         varchar(1000),
    show_illustration   boolean default false        not null,
    publish             boolean default false        not null,
    folder_id           integer                      not null
        references folder
            on delete cascade,
    constraint version_folder_id_version_number_folder_id1_version_number1_key
        unique (folder_id, version_number)
);

alter table version
    owner to admin;

create table user_scope
(
    user_id  integer not null
        references users
            on delete cascade,
    scope_id integer not null
        references scope
            on delete cascade
);

alter table user_scope
    owner to admin;

create table illustration_for_scope
(
    id       integer generated always as identity
        primary key,
    scope_id integer not null
        references scope
            on delete cascade,
    file_id  integer not null
        constraint illustration_for_scope_file_id_file_id1_key
            unique
        references file
            on delete cascade
);

alter table illustration_for_scope
    owner to admin;

create table file_for_version
(
    id         serial
        primary key,
    version_id integer not null
        references version
            on delete cascade,
    file_id    integer not null
        constraint file_for_version_file_id_file_id1_key
            unique
        references file
            on delete cascade
);

alter table file_for_version
    owner to admin;

create table illustration_for_version
(
    id         integer generated always as identity
        primary key,
    version_id integer not null
        references version
            on delete cascade,
    file_id    integer not null
        constraint illustration_for_version_file_id_file_id1_key
            unique
        references file
            on delete cascade
);

alter table illustration_for_version
    owner to admin;

create table role
(
    id        integer generated always as identity
        primary key,
    user_id   integer not null
        references users
            on delete cascade,
    role_name roles   not null
);

alter table role
    owner to admin;

